[MFLOG|0|2025-04-16T23:18:18.712212Z|runtime|05ba5666-6ed9-4c99-b2f1-e3f0fa3d1b7c]<flow ScoringFlow step start> failed:
[MFLOG|0|2025-04-16T23:18:18.715929Z|runtime|fed1fd40-9f29-4ed6-acdd-6bfe02e47f62]    Internal error
[MFLOG|0|2025-04-16T23:18:18.716581Z|runtime|25d2758e-7ad0-43bb-9cb3-d66836cb2d32]Traceback (most recent call last):
[MFLOG|0|2025-04-16T23:18:18.716632Z|runtime|86f79e80-cada-42ca-b530-b22303a7d6c4]  File "/opt/homebrew/anaconda3/envs/mlops/lib/python3.10/site-packages/metaflow/cli.py", line 611, in main
[MFLOG|0|2025-04-16T23:18:18.716677Z|runtime|5967b39e-d758-4619-8900-aa776f1ee44e]    start(auto_envvar_prefix="METAFLOW", obj=state)
[MFLOG|0|2025-04-16T23:18:18.716714Z|runtime|248de646-5ab5-484a-9977-b6c3cd07d178]  File "/opt/homebrew/anaconda3/envs/mlops/lib/python3.10/site-packages/metaflow/_vendor/click/core.py", line 829, in __call__
[MFLOG|0|2025-04-16T23:18:18.716746Z|runtime|6105cd6c-7767-47bc-8e9d-4aeb843cf482]    return self.main(args, kwargs)
[MFLOG|0|2025-04-16T23:18:18.716778Z|runtime|aee68324-60d1-488f-a012-fbfcf1306606]  File "/opt/homebrew/anaconda3/envs/mlops/lib/python3.10/site-packages/metaflow/_vendor/click/core.py", line 782, in main
[MFLOG|0|2025-04-16T23:18:18.716810Z|runtime|0a5150d2-91fa-417a-b9e7-49eea3d9ddb7]    rv = self.invoke(ctx)
[MFLOG|0|2025-04-16T23:18:18.716842Z|runtime|fa089dbb-7c65-4748-a567-e775308511fa]  File "/opt/homebrew/anaconda3/envs/mlops/lib/python3.10/site-packages/metaflow/cli_components/utils.py", line 69, in invoke
[MFLOG|0|2025-04-16T23:18:18.716874Z|runtime|f9309458-010d-41bd-afa5-777bc2f3fd27]    return _process_result(sub_ctx.command.invoke(sub_ctx))
[MFLOG|0|2025-04-16T23:18:18.716903Z|runtime|bc5948b3-c770-4fbf-8076-cb0f611ae7fc]  File "/opt/homebrew/anaconda3/envs/mlops/lib/python3.10/site-packages/metaflow/_vendor/click/core.py", line 1066, in invoke
[MFLOG|0|2025-04-16T23:18:18.716933Z|runtime|72342029-0f7e-41bf-9fa7-454d2bf8681a]    return ctx.invoke(self.callback, ctx.params)
[MFLOG|0|2025-04-16T23:18:18.716961Z|runtime|f56df940-5e27-4f08-9b48-7297a3f55936]  File "/opt/homebrew/anaconda3/envs/mlops/lib/python3.10/site-packages/metaflow/_vendor/click/core.py", line 610, in invoke
[MFLOG|0|2025-04-16T23:18:18.716990Z|runtime|0ea7cdf0-cba6-4814-8b09-34ca1069e4a4]    return callback(args, kwargs)
[MFLOG|0|2025-04-16T23:18:18.859894Z|runtime|19cba181-f447-435b-9b2d-0fcf44f9d5a7]  File "/opt/homebrew/anaconda3/envs/mlops/lib/python3.10/site-packages/metaflow/tracing/__init__.py", line 27, in wrapper_func
[MFLOG|0|2025-04-16T23:18:18.860083Z|runtime|ae389405-bda4-477c-83c4-7c8e562788e5]    return func(args, kwargs)
[MFLOG|0|2025-04-16T23:18:18.860118Z|runtime|6e650d34-1f24-4006-9e7c-d1b61b0851b2]  File "/opt/homebrew/anaconda3/envs/mlops/lib/python3.10/site-packages/metaflow/_vendor/click/decorators.py", line 21, in new_func
[MFLOG|0|2025-04-16T23:18:18.860145Z|runtime|5abd5597-e9bc-47a3-9d8f-174113e0597a]    return f(get_current_context(), args, kwargs)
[MFLOG|0|2025-04-16T23:18:18.860171Z|runtime|15cb5731-ad55-4c14-9133-e65dac7556da]  File "/opt/homebrew/anaconda3/envs/mlops/lib/python3.10/site-packages/metaflow/cli_components/step_cmd.py", line 167, in step
[MFLOG|0|2025-04-16T23:18:18.860196Z|runtime|b825afab-6121-4b42-9a47-6052d7ca7012]    task.run_step(
[MFLOG|0|2025-04-16T23:18:18.860222Z|runtime|1748cbe7-ddf5-4a96-89f7-707d7893275d]  File "/opt/homebrew/anaconda3/envs/mlops/lib/python3.10/site-packages/metaflow/task.py", line 672, in run_step
[MFLOG|0|2025-04-16T23:18:18.860245Z|runtime|f24dd52b-6ca2-4d6e-a742-2b4946229886]    self._exec_step_function(step_func)
[MFLOG|0|2025-04-16T23:18:18.860268Z|runtime|68ca1e74-a8ae-4d60-acca-617eea95bcb2]  File "/opt/homebrew/anaconda3/envs/mlops/lib/python3.10/site-packages/metaflow/task.py", line 62, in _exec_step_function
[MFLOG|0|2025-04-16T23:18:18.860291Z|runtime|634a30e0-34f4-4e38-9789-b3ee342248cb]    step_function()
[MFLOG|0|2025-04-16T23:18:18.860314Z|runtime|9f5948ae-5b8b-401a-8413-44bfafcabbe7]  File "/Users/chinguyen/Desktop/USF-MSDS/msds-603/mlops/src/scoringflow.py", line 12, in start
[MFLOG|0|2025-04-16T23:18:18.860341Z|runtime|bea8d8f2-10d0-4062-b247-50aef689a0da]    self.model = mlflow.sklearn.load_model(model_uri)
[MFLOG|0|2025-04-16T23:18:18.860366Z|runtime|b316b158-4cd8-4c77-9d96-5d5d863eb4c1]  File "/opt/homebrew/anaconda3/envs/mlops/lib/python3.10/site-packages/mlflow/sklearn/__init__.py", line 632, in load_model
[MFLOG|0|2025-04-16T23:18:18.860391Z|runtime|47b7ae77-a888-4c34-81c7-cbe205aa8af0]    local_model_path = _download_artifact_from_uri(artifact_uri=model_uri, output_path=dst_path)
[MFLOG|0|2025-04-16T23:18:18.860415Z|runtime|ef78f67c-8753-4efd-8b76-ad8159e24970]  File "/opt/homebrew/anaconda3/envs/mlops/lib/python3.10/site-packages/mlflow/tracking/artifact_utils.py", line 108, in _download_artifact_from_uri
[MFLOG|0|2025-04-16T23:18:18.860442Z|runtime|74f5a54f-2830-499e-814d-4e5cd28f3051]    repo = get_artifact_repository(artifact_uri=root_uri)
[MFLOG|0|2025-04-16T23:18:18.860465Z|runtime|dc8cc204-cf7f-4cf0-9eec-9cf6ef8135aa]  File "/opt/homebrew/anaconda3/envs/mlops/lib/python3.10/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 133, in get_artifact_repository
[MFLOG|0|2025-04-16T23:18:18.860492Z|runtime|72b2f9a0-9199-4c7a-9450-c62ac5fe3c81]    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
[MFLOG|0|2025-04-16T23:18:18.860515Z|runtime|7e2693c8-db08-49ae-83a4-e14c162913dd]  File "/opt/homebrew/anaconda3/envs/mlops/lib/python3.10/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 78, in get_artifact_repository
[MFLOG|0|2025-04-16T23:18:18.860542Z|runtime|ee642bcf-fb6b-400c-a098-f0891545e32b]    return repository(artifact_uri)
[MFLOG|0|2025-04-16T23:18:18.860565Z|runtime|86b379cb-8fb6-4bd4-b1c0-f172cdcf1b01]  File "/opt/homebrew/anaconda3/envs/mlops/lib/python3.10/site-packages/mlflow/store/artifact/models_artifact_repo.py", line 59, in __init__
[MFLOG|0|2025-04-16T23:18:18.860593Z|runtime|5effba72-c208-4bf4-84ed-3877aad31d61]    ) = ModelsArtifactRepository._get_model_uri_infos(artifact_uri)
[MFLOG|0|2025-04-16T23:18:18.860616Z|runtime|231ef3d7-9788-40c9-8891-fa9f99119c00]  File "/opt/homebrew/anaconda3/envs/mlops/lib/python3.10/site-packages/mlflow/store/artifact/models_artifact_repo.py", line 93, in _get_model_uri_infos
[MFLOG|0|2025-04-16T23:18:18.860640Z|runtime|d6938af8-279d-4fde-889c-fbe0de3ec4d1]    name, version = get_model_name_and_version(client, uri)
[MFLOG|0|2025-04-16T23:18:18.860664Z|runtime|7e664f14-05cd-43db-b15b-7ec85ed58a8d]  File "/opt/homebrew/anaconda3/envs/mlops/lib/python3.10/site-packages/mlflow/store/artifact/utils/models.py", line 94, in get_model_name_and_version
[MFLOG|0|2025-04-16T23:18:18.860692Z|runtime|d3ba115c-99ee-4bca-a732-dfb78487deb6]    return model_name, str(_get_latest_model_version(client, model_name, model_stage))
[MFLOG|0|2025-04-16T23:18:18.860715Z|runtime|cfdb2619-ba81-43bb-92ff-8361f958bed7]  File "/opt/homebrew/anaconda3/envs/mlops/lib/python3.10/site-packages/mlflow/store/artifact/utils/models.py", line 35, in _get_latest_model_version
[MFLOG|0|2025-04-16T23:18:18.860738Z|runtime|edf9ec98-84e6-4b67-9b1f-ccefb38cde4f]    raise MlflowException(f"No versions of model with name '{name}'{stage_str} found")
[MFLOG|0|2025-04-16T23:18:18.860760Z|runtime|d49ce37f-5393-40b9-ab7e-33f0eac13b28]mlflow.exceptions.MlflowException: No versions of model with name 'BestModel-MetaflowLab' and stage 'Production' found
[MFLOG|0|2025-04-16T23:18:18.860785Z|runtime|143583b6-78be-4303-8fb3-a82db978f4fe]
[MFLOG|0|2025-04-16T23:18:18.861215Z|runtime|bf51a667-1c90-40b9-a841-01590f1b400e]Task failed.